#!/usr/bin/env sh

gitsup_config ()
{
	git config --get-all "${1:-}"
}

gitsup_fetch_args ()
{
	default_args="--all"
	user_args=$(gitsup_config sup.fetchargs)

	echo "${user_args:-${default_args}}"
}

gitsup_ignored_remotes ()
{
	ignore_list=$(gitsup_config sup.ignoreremote)
	ignore_chain=""
	for remote in $ignore_list
	do
		ignore_chain="${ignore_chain} | grep -v ${remote}"
	done

	echo "$ignore_chain"
}

gitsup_paths ()
{
	directory="${1:-}"
	depth=2

	find "${directory}" -name .git -depth ${depth} 2>/dev/null | sort
}

for path in $(gitsup_paths "${1:-}")
do
	cd "${path}/.." || exit 2
	pwd
	git fetch "$(gitsup_fetch_args)" "$(gitsup_ignored_remotes)" | sed "s/^/    /"
	cd - > /dev/null 2>&1 || exit 2
done
